"""Defines end-points to access functionalities related to the reference point method."""

from typing import Annotated
import polars as pl


from fastapi import APIRouter, Depends, HTTPException, status
from sqlmodel import Session, select

from desdeo.api.models.generic import SolutionInfo

from desdeo.explanations.explainer import ShapExplainer
from desdeo.explanations.utils import generate_biased_mean_data
from desdeo.mcdm.nimbus import generate_starting_point

from desdeo.api.db import get_session
from desdeo.api.models import (
    InteractiveSessionDB,
    ProblemDB,
    SolutionReference,
    StateDB,
    User,
    UserSavedSolutionDB,
    ReferencePoint,
    RXIMOExplainRequest,
    RXIMOExplainResponse,
)
from desdeo.api.routers.user_authentication import get_current_user
from desdeo.mcdm import rpm_solve_solutions
from desdeo.problem import Problem
from desdeo.tools import SolverResults
from desdeo.api.routers.nimbus import (
    filter_duplicates,
    collect_saved_solutions,
    collect_all_solutions,
)

from desdeo.api.utils.reference_data import (
    get_reference_data_as_dataframe,
    get_reference_point_symbols,
)


router = APIRouter(prefix="/method/rximo")


@router.post("/explain", response_model=RXIMOExplainResponse)
def explain_rximo(
    request: RXIMOExplainRequest,
    user: Annotated[User, Depends(get_current_user)],
    session: Annotated[Session, Depends(get_session)],
):
    """Explain the RXIMO method using SHAP values.

    This endpoint explains the RXIMO method using SHAP values. The explanation is based on a dataset
    that simulates the inputs and outputs of the RXIMO method. The inputs are the reference points,
    and the outputs are the solutions generated by the method for those reference points.

    The explanation is performed by computing SHAP values that indicate how each input (reference point)
    influences each output (solution objective value). The SHAP values are computed using a background
    dataset that represents the expected behavior of the method.

    Args:
        request (RXIMOExplainRequest): The request body containing:
            - problem_id (int): The ID of the problem to explain.
            - state_id (int): The ID of the state associated with the interactive session.
            - session_id (int): The ID of the interactive session.
            - input_symbols (list[str]): The input symbols representing reference points.
            - output_symbols (list[str]): The output symbols representing solution objectives.
            - background_data (pl.DataFrame): The background data for SHAP value computation.
            - simulation_data (pl.DataFrame): The simulation data to train the explainer.
        current_user (User): The currently authenticated user.
        session (Session): The database session.

    Returns:
        RXIMOExplainResponse: The response containing SHAP values and related information.

    Raises:
        HTTPException: If any validation or processing error occurs.
    """

    if request.session_id is not None:
        statement = select(InteractiveSessionDB).where(
            InteractiveSessionDB.id == request.session_id
        )
        interactive_session = session.exec(statement)

        if interactive_session is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Could not find interactive session with id={request.session_id}.",
            )
    else:
        # request.session_id is None:
        # use active session instead
        statement = select(InteractiveSessionDB).where(
            InteractiveSessionDB.id == user.active_session_id
        )

        interactive_session = session.exec(statement).first()

    # fetch the problem from the DB
    statement = select(ProblemDB).where(
        ProblemDB.user_id == user.id, ProblemDB.id == request.problem_id
    )
    problem_db = session.exec(statement).first()

    if problem_db is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Problem with id={request.problem_id} could not be found.",
        )

    problem = Problem.from_problemdb(problem_db)

    # fetch parent state
    if request.parent_state_id is None:
        # parent state is assumed to be the last state added to the session.
        parent_state = (
            interactive_session.states[-1]
            if (interactive_session is not None and len(interactive_session.states) > 0)
            else None
        )

    else:
        # request.parent_state_id is not None
        statement = select(StateDB).where(StateDB.id == request.parent_state_id)
        parent_state = session.exec(statement).first()

        if parent_state is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Could not find state with id={request.parent_state_id}",
            )

    print("Starting explanation process...")
    df = get_reference_data_as_dataframe(session, request.problem_id)
    print("Reference data loaded, shape:", df.shape)

    input_symbols, output_symbols = get_reference_point_symbols(len(problem.objectives))
    print(f"Input symbols: {input_symbols}")
    print(f"Output symbols: {output_symbols}")

    print("Creating ShapExplainer model...")
    model = ShapExplainer(
        problem_data=df,
        input_symbols=input_symbols,
        output_symbols=output_symbols,
    )
    print("ShapExplainer model created")

    print("Processing target data...")
    # Convert dictionary values to numpy array
    target_array = list(request.preference.aspiration_levels.values())
    print("Target array:", target_array)
    # Make target a dictionary with the input symbols
    target = dict(zip(input_symbols, target_array))
    print("Target dictionary created:", target)

    print("Generating background data...")
    try:
        # Use a smaller max_size and the OSQP solver with a timeout
        background_subset = generate_biased_mean_data(
            df[output_symbols].to_numpy(),
            target_array,
            min_size=2,  # minimum subset size
            max_size=10,  # limit max subset size
            solver="OSQP",  # try a different solver
        )
        if background_subset is None:
            raise ValueError("Could not find a suitable background subset")
        print("Background data generated, size:", len(background_subset))
    except Exception as e:
        print(f"Error generating background data: {str(e)}")
        # Fallback: use a simple random subset if optimization fails
        import numpy as np

        n_samples = min(10, len(df))
        background_subset = np.random.choice(len(df), size=n_samples, replace=False)
        print("Using fallback random background data, size:", len(background_subset))

    print("Setting up model with background data...")
    model.setup(background_data=pl.DataFrame(df[background_subset]))
    print("Model setup complete")

    print("Computing SHAP values...")
    try:
        shaps = model.explain_input(pl.DataFrame(target))
        print("SHAP values computed successfully")
        print(
            f"SHAP values shape: {shaps.values.shape if hasattr(shaps.values, 'shape') else 'no shape'}"
        )

        # Convert SHAP values to a format that can be serialized
        shap_values = {}
        import numpy as np

        # Convert to numpy array first and ensure it's float type
        values = np.array(shaps.values, dtype=np.float64)
        print(f"Raw values shape: {values.shape}")
        print(f"Raw values type: {values.dtype}")

        # Handle different array shapes
        if len(values.shape) == 3:
            # Shape is (samples, outputs, inputs)
            # For each output, calculate mean impact from inputs
            for i, sym in enumerate(output_symbols):
                mean_impact = np.mean(
                    values[0, i, :]
                )  # Average over inputs for first sample
                print(f"Mean impact for {sym}: {mean_impact}")
                shap_values[sym] = float(
                    mean_impact
                )  # Explicitly convert to Python float
        elif len(values.shape) == 2:
            # If we have a 2D array (samples × features)
            for i, sym in enumerate(output_symbols):
                shap_values[sym] = float(np.asscalar(values[0, i]))
        else:
            # If we have a 1D array (features)
            for i, sym in enumerate(output_symbols):
                shap_values[sym] = float(np.asscalar(values[i]))  # Get base values
        base_values = {}
        base_vals = np.array(
            shaps.base_values, dtype=np.float64
        )  # Convert to numpy array with float type
        print(f"Base values shape: {base_vals.shape}")
        print(f"Base values type: {base_vals.dtype}")

        for i, sym in enumerate(output_symbols):
            if len(base_vals.shape) > 0:  # If it's an array
                base_val = float(
                    np.asscalar(base_vals[i])
                    if i < len(base_vals)
                    else np.mean(base_vals)
                )
                print(f"Base value for {sym}: {base_val}")
                base_values[sym] = base_val
            else:  # If it's a scalar
                base_val = float(np.asscalar(base_vals))
                print(f"Base value for {sym}: {base_val}")
                base_values[sym] = base_val

        # Convert explained data
        explained_data = {}
        for sym in input_symbols:
            explained_data[sym] = float(target.get(sym, 0.0))

        print("Data conversion successful")
        print(f"Converted SHAP values: {shap_values}")
        print(f"Converted base values: {base_values}")
        print(f"Converted explained data: {explained_data}")

        return RXIMOExplainResponse(
            shap_values=shap_values,
            base_values=base_values,
            explained_data=explained_data,
        )
    except Exception as e:
        print(f"Error in SHAP computation: {str(e)}")
        # Return a simplified response if SHAP computation fails
        default_value = 0.0
        return RXIMOExplainResponse(
            shap_values={sym: default_value for sym in output_symbols},
            base_values={sym: default_value for sym in output_symbols},
            explained_data={
                sym: float(target.get(sym, default_value)) for sym in input_symbols
            },
        )
