"""Models specific to the reference point method."""

from sqlmodel import JSON, Column, Field, SQLModel

from .generic import SolutionInfo
from .preference import ReferencePoint
from .generic_states import SolutionReferenceResponse


class RPMSolveRequest(SQLModel):
    """Model of the request to the reference point method."""

    problem_id: int
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    scalarization_options: dict[str, float | str | bool] | None = Field(
        sa_column=Column(JSON), default=None
    )
    solver: str | None = Field(default=None)
    solver_options: dict[str, float | str | bool] | None = Field(
        sa_column=Column(JSON), default=None
    )
    preference: ReferencePoint = Field(Column(JSON))


class RPMSolveResponse(SQLModel):
    """The response from the RPM solve endpoint."""

    state_id: int | None = Field(description="The newly created state id")
    previous_preference: ReferencePoint = Field(
        description="The previous preference used."
    )
    current_solutions: list[SolutionReferenceResponse] = Field(
        description="The solutions from the current iteration of RPM."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="The best candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by RPM in all iterations."
    )


class RPMSaveRequest(SQLModel):
    """Request model for saving solutions from any method's state."""

    problem_id: int
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    solution_info: list[SolutionInfo]


class RPMSaveResponse(SQLModel):
    """The response from NIMBUS save endpoint."""

    state_id: int | None = Field(description="The id of the newest state")


class RPMInitializationRequest(SQLModel):
    """Model of the request to the RPM method."""

    problem_id: int
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    starting_point: ReferencePoint | SolutionInfo | None = Field(
        sa_column=Column(JSON), default=None
    )
    scalarization_options: dict[str, float | str | bool] | None = Field(
        sa_column=Column(JSON), default=None
    )
    solver: str | None = Field(default=None)
    solver_options: dict[str, float | str | bool] | None = Field(
        sa_column=Column(JSON), default=None
    )


class RPMInitializationResponse(SQLModel):
    """The response from NIMBUS classification endpoint."""

    state_id: int | None = Field(description="The newly created state id")
    current_solutions: list[SolutionReferenceResponse] = Field(
        description="The solutions from the current interation of nimbus."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="The best candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by NIMBUS in all iterations."
    )
