"""Models specific to the reference point method."""

from typing import Literal

from sqlmodel import JSON, Column, Field, SQLModel

from .generic import SolutionInfo
from .generic_states import SolutionReferenceResponse
from .preference import ReferencePoint


class RPMSolveRequest(SQLModel):
    """Model of the request to the reference point method."""

    problem_id: int
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    scalarization_options: dict[str, float | str | bool] | None = Field(
        sa_column=Column(JSON), default=None
    )
    solver: str | None = Field(default=None)
    solver_options: dict[str, float | str | bool] | None = Field(
        sa_column=Column(JSON), default=None
    )
    preference: ReferencePoint = Field(Column(JSON))


class RPMSaveRequest(SQLModel):
    """Request model for saving solutions from any method's state."""

    problem_id: int
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    solution_info: list[SolutionInfo]


class RPMDeleteSaveRequest(SQLModel):
    """Request model for deletion of a saved solution."""

    state_id: int = Field(description="The ID of the save state.")
    solution_index: int = Field(
        description="The ID of the solution within the above state."
    )
    problem_id: int = Field(description="The ID of the problem.")


class RPMFinalizeRequest(SQLModel):
    """Request model for finalizing the RPM procedure."""

    problem_id: int
    session_id: int | None = Field(default=None)
    parent_state_id: int | None = Field(default=None)

    solution_info: SolutionInfo  # the final solution


class RPMSolveResponse(SQLModel):
    """The response from RPM solve endpoint."""

    response_type: Literal["rpm.solve"] = "rpm.solve"

    state_id: int | None = Field(description="The newly created state id")
    previous_preference: ReferencePoint = Field(
        description="The previous preference used."
    )
    perturbed_reference_points: list[ReferencePoint] = Field(
        description="The perturbed reference points used to generate the current solutions."
    )
    current_solutions: list[SolutionReferenceResponse] = Field(
        description="The solutions from the current iteration of nimbus."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="The best candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by NIMBUS in all iterations."
    )


class RPMSaveResponse(SQLModel):
    """The response from RPM save endpoint."""

    response_type: Literal["rpm.save"] = "rpm.save"

    state_id: int | None = Field(description="The id of the newest state")


class RPMDeleteSaveResponse(SQLModel):
    """Response of RPM save deletion."""

    response_type: str = "rpm.delete_save"

    message: str | None = None


class RPMFinalizeResponse(SQLModel):
    """The response from RPM finalize endpoint."""

    response_type: Literal["rpm.finalize"] = "rpm.finalize"

    state_id: int | None = Field(description="The newly created state id")
    final_solution: SolutionReferenceResponse = Field(
        description="The final solution. We do not need the other current solutions."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="The best candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by RPM in all iterations."
    )


class RPMIntermediateSolutionResponse(SQLModel):
    """The response from RPM classification endpoint."""

    response_type: Literal["rpm.intermediate"] = "rpm.intermediate"

    state_id: int | None = Field(description="The newly created state id")
    reference_solution_1: dict[str, float] = Field(
        sa_column=Column(JSON),
        description="The first solution used when computing intermediate points.",
    )
    reference_solution_2: dict[str, float] = Field(
        sa_column=Column(JSON),
        description="The second solution used when computing intermediate points.",
    )
    current_solutions: list[SolutionReferenceResponse] = Field(
        description="The solutions from the current iteration of RPM."
    )
    saved_solutions: list[SolutionReferenceResponse] = Field(
        description="The best candidate solutions saved by the decision maker."
    )
    all_solutions: list[SolutionReferenceResponse] = Field(
        description="All solutions generated by RPM in all iterations."
    )
