"""Explainers are defined here."""

import numpy as np
import polars as pl
import shap
from scipy.spatial import cKDTree


class ShapExplainer:
    """Defines a SHAP explainer for reference point based methods."""

    def __init__(self, problem_data: pl.DataFrame, input_symbols: list[str], output_symbols: list[str]):
        """Initialize the explainer.

        Initializes the explainer with given data, and input and output symbols.
        The data should contain the columns listed in the input and output symbols.
        This data is then used to simulate the inputs and outputs of an (interactive)
        multiobjective optimization method, which is used to explain the relation of its
        inputs and outputs using SHAP values.

        Note:
            The `data` can be generated by for a reference point based based by, e.g.,
            randomly sampling the input space and then evaluating the methods with the
            sampled inputs to generate outputs.

        Args:
            problem_data (pl.DataFrame): the data to simulate the input and
                outputs of a multiobjective optimization method.
            input_symbols (list[str]): the input symbols present in `data`.
                These symbols represent the inputs to the method.
            output_symbols (list[str]): the output symbols present in `data`.
                These symbols represent the outputs of the method.
        """
        self.data = problem_data
        self.input_symbols = input_symbols
        self.output_symbols = output_symbols
        self.input_array = self.data[self.input_symbols].to_numpy()
        self.output_array = self.data[self.output_symbols].to_numpy()
        self.to_output_tree = cKDTree(self.input_array)
        self.explainer = None

    def setup(self, background_data: pl.DataFrame):
        """Setup the explainer.

        Setups the SHAP explainer with  the given background data. The
        background data should have the columns `self.input_symbols`. The
        background data is used as the background (or missing data) when
        computing SHAP values.  The mean (or expected values) of the background
        data's output (`self.output_symbols`) will determine the baseline of the
        SHAP values.

        Note:
            To generate a dataset with meaningful expected values, e.g., in case
            the SHAP values are better understood by relating them to a specific baseline,
            see `desdeo.explanations.generate_biased_mean_data`.

        Args:
            background_data (pl.DataFrame): the background data.
        """
        self.explainer = shap.Explainer(
            self.evaluate,
            masker=background_data[self.input_symbols].to_numpy(),
        )

    def setup_with_baseline(self, baseline_point: np.ndarray | pl.DataFrame):
        r"""Setup the explainer using a single point as the baseline.

        Instead of providing a full background dataset, this method uses a
        single point as the SHAP background. This is appropriate when the
        Exact SHAP algorithm is in use (which `shap.Explainer` selects
        automatically for problems with at most ~10 inputs): the Exact
        algorithm computes exact SHAP values regardless of background size,
        and the background only affects the base value $\\phi_0$.

        For R-XIMO, a natural choice is the current solution (or its
        corresponding reference point), which makes $\\phi_0$ equal to the
        prediction at that baseline; the SHAP values then explain how the
        new reference point pushed the solution away from this baseline.

        Args:
            baseline_point (np.ndarray | pl.DataFrame): a single-point
                baseline. May be a 1D numpy array of length
                ``len(self.input_symbols)``, a 2D array of shape
                ``(1, len(self.input_symbols))``, or a polars DataFrame with
                a single row containing the columns in ``self.input_symbols``.
        """
        if isinstance(baseline_point, pl.DataFrame):
            baseline_array = baseline_point[self.input_symbols].to_numpy()
        else:
            baseline_array = np.asarray(baseline_point, dtype=float)
            if baseline_array.ndim == 1:
                baseline_array = baseline_array.reshape(1, -1)

        if baseline_array.shape != (1, len(self.input_symbols)):
            raise ValueError(
                f"baseline_point must contain exactly one row of length "
                f"{len(self.input_symbols)}, got shape {baseline_array.shape}."
            )

        self.explainer = shap.Explainer(self.evaluate, masker=baseline_array)

    def setup_with_shifted_background(self, background_data: pl.DataFrame, target_mean: np.ndarray):
        """Setup the explainer with background data shifted to a target mean.

        Computationally cheap alternative to
        :func:`desdeo.explanations.generate_biased_mean_data`. Rather than
        solving an MIQP to find a subset whose mean is close to a target,
        this shifts every row of the background data by a constant so that
        the resulting background has its mean exactly equal to
        ``target_mean``.

        Args:
            background_data (pl.DataFrame): the background data to shift.
                Must contain the columns ``self.input_symbols``.
            target_mean (np.ndarray): desired mean for the shifted
                background, ordered by ``self.input_symbols``.
        """
        target = np.asarray(target_mean, dtype=float).reshape(-1)
        if target.size != len(self.input_symbols):
            raise ValueError(f"target_mean must have length {len(self.input_symbols)}, got {target.size}.")

        bg = background_data[self.input_symbols].to_numpy()
        shifted = bg - bg.mean(axis=0) + target
        shifted_df = pl.DataFrame({sym: shifted[:, i] for i, sym in enumerate(self.input_symbols)})
        self.setup(background_data=shifted_df)

    def evaluate(self, evaluate_array: np.ndarray) -> np.ndarray:
        """Evaluates the multiobjective optimization method represented by the data.

        Note:
            Evaluation happens by finding the closest matching input array in the
            `self.input_array` and then using that value's corresponding output
            as the evaluation result. Closest means lowest Euclidean distance.

        Args:
            evaluate_array (np.ndarray): the inputs to the method represented by the data.
                Can be either a single input, or an array of multiple inputs. Used mainly by
                `self.explain_input`.

        Returns:
            np.ndarray: the evaluated output(s) corresponding to the input data.
        """
        _, indices = self.to_output_tree.query(evaluate_array)

        return self.output_array[indices]

    def explain_input(self, to_be_explained: pl.DataFrame) -> dict:
        """Explain an input and produces SHAP values.

        Args:
            to_be_explained (pl.DataFrame): the input to be explained. The
                dataframe must have the columns defined in `self.input_symbols`.

        Returns:
            dict: the key 'shaps' corresponds to the computed SHAP values for
                the input, the key 'base_values' is the baseline the SHAP values
                were computed against, and the key 'data' is the input the SHAP
                values were computed for.
        """
        _to_be_explained = to_be_explained[self.input_symbols].to_numpy()

        return self.explainer(_to_be_explained)
