"""Explainers are defined here."""

from collections.abc import Callable

import numpy as np
import polars as pl
import shap
from scipy.spatial import cKDTree
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel, WhiteKernel


def make_gp_surrogate(
    input_array: np.ndarray,
    output_array: np.ndarray,
    *,
    length_scale: float = 1.0,
    length_scale_bounds: tuple[float, float] = (1e-2, 1e2),
    noise_level: float = 1e-6,
    normalize_y: bool = True,
) -> Callable[[np.ndarray], np.ndarray]:
    r"""Build a smooth Gaussian-process surrogate for a multi-output mapping.

    Fits one independent `sklearn.gaussian_process.GaussianProcessRegressor`
    per output column. Hyperparameters are learned by maximum marginal
    likelihood. The returned callable accepts a 1D array of shape ``(k,)``
    or a 2D array of shape ``(n, k)`` and returns predictions of shape
    ``(n, m)`` where ``m`` is the number of output columns. With small
    twice-differentiable problems a GP is a much better proxy for the
    underlying scalarization solver than a 1-NN lookup: it is smooth between
    samples, extrapolates gracefully outside the training cloud, and yields
    less step-discontinuous SHAP values.

    Args:
        input_array (np.ndarray): training inputs of shape ``(n, k)``.
        output_array (np.ndarray): training outputs of shape ``(n, m)``.
        length_scale (float): initial RBF length scale; refit by MLE.
        length_scale_bounds (tuple[float, float]): MLE bounds on the
            length scale per dimension.
        noise_level (float): white-noise floor of the kernel.
        normalize_y (bool): center each output column before fitting.

    Returns:
        Callable[[np.ndarray], np.ndarray]: a function suitable for
            ``ShapExplainer.evaluate``.
    """
    # Local import to keep the optional sklearn dependency optional.

    kernel = ConstantKernel(1.0) * RBF(length_scale=length_scale, length_scale_bounds=length_scale_bounds)
    kernel = kernel + WhiteKernel(noise_level=noise_level, noise_level_bounds=(1e-10, 1e-1))

    gps = []
    for i in range(output_array.shape[1]):
        gp = GaussianProcessRegressor(
            kernel=kernel,
            alpha=1e-10,
            normalize_y=normalize_y,
            n_restarts_optimizer=2,
        )
        gp.fit(input_array, output_array[:, i])
        gps.append(gp)

    def predict(x: np.ndarray) -> np.ndarray:
        arr = np.asarray(x, dtype=float)
        if arr.ndim == 1:
            arr = arr.reshape(1, -1)
        return np.column_stack([gp.predict(arr) for gp in gps])

    return predict


class ShapExplainer:
    """Defines a SHAP explainer for reference point based methods."""

    def __init__(
        self,
        problem_data: pl.DataFrame,
        input_symbols: list[str],
        output_symbols: list[str],
        *,
        surrogate_model: Callable[[np.ndarray], np.ndarray] | None = None,
    ):
        """Initialize the explainer.

        Initializes the explainer with given data, and input and output symbols.
        The data should contain the columns listed in the input and output symbols.
        This data is then used to simulate the inputs and outputs of an (interactive)
        multiobjective optimization method, which is used to explain the relation of its
        inputs and outputs using SHAP values.

        Note:
            The `data` can be generated by for a reference point based based by, e.g.,
            randomly sampling the input space and then evaluating the methods with the
            sampled inputs to generate outputs.

        Args:
            problem_data (pl.DataFrame): the data to simulate the input and
                outputs of a multiobjective optimization method.
            input_symbols (list[str]): the input symbols present in `data`.
                These symbols represent the inputs to the method.
            output_symbols (list[str]): the output symbols present in `data`.
                These symbols represent the outputs of the method.
            surrogate_model (Callable | None): optional smooth surrogate
                taking inputs of shape ``(n, k)`` and returning outputs of
                shape ``(n, m)``. When ``None``, ``evaluate`` falls back to
                a piecewise-constant nearest-neighbor lookup over
                ``problem_data``. See :func:`make_gp_surrogate` for a
                ready-made Gaussian-process surrogate.
        """
        self.data = problem_data
        self.input_symbols = input_symbols
        self.output_symbols = output_symbols
        self.input_array = self.data[self.input_symbols].to_numpy()
        self.output_array = self.data[self.output_symbols].to_numpy()
        self.to_output_tree = cKDTree(self.input_array)
        self.surrogate_model = surrogate_model
        self.explainer = None

    def setup(self, background_data: pl.DataFrame):
        """Setup the explainer.

        Setups the SHAP explainer with  the given background data. The
        background data should have the columns `self.input_symbols`. The
        background data is used as the background (or missing data) when
        computing SHAP values.  The mean (or expected values) of the background
        data's output (`self.output_symbols`) will determine the baseline of the
        SHAP values.

        Note:
            To generate a dataset with meaningful expected values, e.g., in case
            the SHAP values are better understood by relating them to a specific baseline,
            see `desdeo.explanations.generate_biased_mean_data`.

        Args:
            background_data (pl.DataFrame): the background data.
        """
        self.explainer = shap.Explainer(
            self.evaluate,
            masker=background_data[self.input_symbols].to_numpy(),
        )

    def setup_with_baseline(self, baseline_point: np.ndarray | pl.DataFrame):
        r"""Setup the explainer using a single point as the baseline.

        Instead of providing a full background dataset, this method uses a
        single point as the SHAP background. This is appropriate when the
        Exact SHAP algorithm is in use (which `shap.Explainer` selects
        automatically for problems with at most ~10 inputs): the Exact
        algorithm computes exact SHAP values regardless of background size,
        and the background only affects the base value $\\phi_0$.

        For R-XIMO, a natural choice is the current solution (or its
        corresponding reference point), which makes $\\phi_0$ equal to the
        prediction at that baseline; the SHAP values then explain how the
        new reference point pushed the solution away from this baseline.

        Args:
            baseline_point (np.ndarray | pl.DataFrame): a single-point
                baseline. May be a 1D numpy array of length
                ``len(self.input_symbols)``, a 2D array of shape
                ``(1, len(self.input_symbols))``, or a polars DataFrame with
                a single row containing the columns in ``self.input_symbols``.
        """
        if isinstance(baseline_point, pl.DataFrame):
            baseline_array = baseline_point[self.input_symbols].to_numpy()
        else:
            baseline_array = np.asarray(baseline_point, dtype=float)
            if baseline_array.ndim == 1:
                baseline_array = baseline_array.reshape(1, -1)

        if baseline_array.shape != (1, len(self.input_symbols)):
            raise ValueError(
                f"baseline_point must contain exactly one row of length "
                f"{len(self.input_symbols)}, got shape {baseline_array.shape}."
            )

        self.explainer = shap.Explainer(self.evaluate, masker=baseline_array)

    def setup_with_shifted_background(self, background_data: pl.DataFrame, target_mean: np.ndarray):
        """Setup the explainer with background data shifted to a target mean.

        Computationally cheap alternative to
        :func:`desdeo.explanations.generate_biased_mean_data`. Rather than
        solving an MIQP to find a subset whose mean is close to a target,
        this shifts every row of the background data by a constant so that
        the resulting background has its mean exactly equal to
        ``target_mean``.

        Args:
            background_data (pl.DataFrame): the background data to shift.
                Must contain the columns ``self.input_symbols``.
            target_mean (np.ndarray): desired mean for the shifted
                background, ordered by ``self.input_symbols``.
        """
        target = np.asarray(target_mean, dtype=float).reshape(-1)
        if target.size != len(self.input_symbols):
            raise ValueError(f"target_mean must have length {len(self.input_symbols)}, got {target.size}.")

        bg = background_data[self.input_symbols].to_numpy()
        shifted = bg - bg.mean(axis=0) + target
        shifted_df = pl.DataFrame({sym: shifted[:, i] for i, sym in enumerate(self.input_symbols)})
        self.setup(background_data=shifted_df)

    def evaluate(self, evaluate_array: np.ndarray) -> np.ndarray:
        """Evaluates the multiobjective optimization method represented by the data.

        Note:
            When a ``surrogate_model`` was passed to the constructor, the
            evaluation delegates to it (the surrogate is expected to return
            an array of shape ``(n, m)`` for an input of shape ``(n, k)``).
            Otherwise the evaluation falls back to a piecewise-constant
            nearest-neighbor lookup: it finds the closest matching input
            array in ``self.input_array`` (lowest Euclidean distance) and
            returns the corresponding stored output.

        Args:
            evaluate_array (np.ndarray): the inputs to the method represented by the data.
                Can be either a single input, or an array of multiple inputs. Used mainly by
                `self.explain_input`.

        Returns:
            np.ndarray: the evaluated output(s) corresponding to the input data.
        """
        if self.surrogate_model is not None:
            arr = np.asarray(evaluate_array, dtype=float)
            single = arr.ndim == 1
            if single:
                arr = arr.reshape(1, -1)
            out = np.asarray(self.surrogate_model(arr))
            return out[0] if single else out
        _, indices = self.to_output_tree.query(evaluate_array)

        return self.output_array[indices]

    def explain_input(self, to_be_explained: pl.DataFrame) -> dict:
        """Explain an input and produces SHAP values.

        Args:
            to_be_explained (pl.DataFrame): the input to be explained. The
                dataframe must have the columns defined in `self.input_symbols`.

        Returns:
            dict: the key 'shaps' corresponds to the computed SHAP values for
                the input, the key 'base_values' is the baseline the SHAP values
                were computed against, and the key 'data' is the input the SHAP
                values were computed for.
        """
        _to_be_explained = to_be_explained[self.input_symbols].to_numpy()

        return self.explainer(_to_be_explained)
